In [5]:
import numpy as np
pre_para = np.load('/Volumes/FAIR/DC-Image-Analysis/DC-project-master/cleancode/NewMidplane/Final_preop.npy')
post_para = np.load('/Volumes/FAIR/DC-Image-Analysis/DC-project-master/cleancode/NewMidplane/Final_postop.npy')

In [ ]:
### Un-reshaping the a,b,c normal vector seems to make no big difference
### orientation of plane will be minorly altered. But there's no need to
### results already good enough.

In [3]:
import nibabel as nib
import core
import Functions
from time import time
import os
import numpy as np


paths = ['/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleC/SC_Follow.nrrd',
         '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleD/SD_Post-op.nrrd',
         '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleG/SG_Post-op.nrrd',
         '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleH/SH_Post-op.nrrd',
         '/Users/fair00542/Desktop/TestImages/ScanJ/1.2.392.200036.9116.2.6.1.48.1221600807.1432222275.897467.dcm']
# paths =['/Volumes/FAIR/Sinead/DC-Project-Images/original/Sample3/S3_Pre-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleF/SF_Pre-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleG/SG_Pre-op.nrrd',
#         '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleB/SB_Pre-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleC/SC_Pre-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleD/SD_Pre-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleH/SH_Pre-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleI/SI_Pre-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/Sample4/S4_Pre-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/Sample5/S5_Pre_rigid.nrrd',
#          '/Users/fair00542/Desktop/TestImages/ScanA/1.3.12.2.1107.5.1.4.54053.30000014091206552395300024468.dcm',
#          '/Users/fair00542/Desktop/TestImages/ScanB/1.3.12.2.1107.5.1.4.51967.30000014110308064564000003663.dcm',
#          '/Users/fair00542/Desktop/TestImages/ScanC/1.3.12.2.1107.5.1.4.95198.30000014121008232151100020392.dcm',
#          '/Users/fair00542/Desktop/TestImages/ScanD/1.3.12.2.1107.5.1.4.95198.30000015040208110913600035430.dcm',
#          '/Users/fair00542/Desktop/TestImages/ScanE/1.3.12.2.1107.5.1.4.95198.30000015061008243097400047439.dcm',
#          '/Users/fair00542/Desktop/TestImages/ScanF/1.3.12.2.1107.5.1.4.95198.30000015051507521609300034666.dcm',
#          '/Users/fair00542/Desktop/TestImages/ScanG/1.3.12.2.1107.5.1.4.95198.30000015072708211605400036464.dcm',
#          '/Users/fair00542/Desktop/TestImages/ScanH/1.2.840.113619.2.55.3.2634693835.766.1437720278.192.2.dcm',
#          '/Users/fair00542/Desktop/TestImages/ScanI/1.3.12.2.1107.5.1.4.95198.30000015071109310409300075668.dcm',
#          '/Users/fair00542/Desktop/TestImages/ScanJ/1.2.392.200036.9116.2.6.1.48.1221600807.1432222275.897467.dcm']
# paths = ['/Volumes/FAIR/Sinead/DC-Project-Images/original/Sample2/S2_Post-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/Sample3/S3_Post-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/Sample4/S4_Post-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/Sample5/S5_Post-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleB/SB_Post-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleC/SC_Post-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleD/SD_Post-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleF/SF_Post-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleG/SG_Post-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleH/SH_Post-op.nrrd',
#          '/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleI/SI_Post-op.nrrd']


para_List = []
# for pathnumber in range(0,len(paths)):
for pathnumber in range(2,3):
    path = paths[pathnumber]
    print 'iteration number', pathnumber
    if path.endswith('.nii') or path.endswith('.nii.gz'):
        import core
        array, ConstPixelSpacing, affine = core.nifti2np(path)
    #     bone = core.thresholdnp(array, 1100, 1500)
    #     softtissue  = core.thresholdnp(array, 0, 80)
        # visual     = core.thresholdnp(self.scan.array, -100, 1500)

    elif path.endswith('.dcm'):
        import core
        array, ConstPixelSpacing, origin, path, affine = core.dicom2np(path)
#         maskPath = os.path.join(os.path.split(os.path.dirname(path))[0], 'level2.nii.gz')
#         skullPath = os.path.join(os.path.dirname(path), 'skull_contour.nii.gz')
        array=np.swapaxes(array, 0, 1)
        bone = core.thresholdnp(array, 1100, 1500)
        softtissue  = core.thresholdnp(array, 0, 80)

    elif path.endswith('.nrrd'):
        import core
        array, ConstPixelSpacing, affine = core.nrrd2np(path)
#         array=np.swapaxes(array, 0, 1)
#         bone = core.thresholdnp(array, 800, 1500)
        bone = core.thresholdnp(array, 1100, 1500)
        softtissue  = core.thresholdnp(array, 0, 80)
#         maskPath = os.path.join(os.path.dirname(path), 'level2.nii.gz')
#         skullPath = os.path.join(os.path.dirname(path), 'skull_contour.nii.gz')

def saveMask(array, path, name):
    mask = array.astype(np.float64)
#     mask = np.swapaxes(mask, 0, 1)
    img = nib.Nifti1Image(mask, affine)
    savePath = os.path.join(os.path.split(path)[0], '{}.nii.gz'.format(name))
    nib.save(img, savePath)
t0 = time()
boneReshaped = core.reshape(bone, ConstPixelSpacing)
# softtissueReshaped = core.reshape(softtissue,ConstPixelSpacing)
arrayReshaped = core.reshape(array,ConstPixelSpacing)

# get coordinates of bones
X = np.where(boneReshaped>0)
X_array = np.where(arrayReshaped>0)
# this step exchanges the x y axis.
X = np.matrix(np.column_stack((X[0],X[1],X[2])))
X_array = np.matrix(np.column_stack((X_array[0],X_array[1],X_array[2])))
# Feature Normalization for X matrix
os.chdir('/Volumes/FAIR/DC-Image-Analysis/DC-project-master/cleancode/NewMidplane')
import Functions
# X_norm,mu,std = Functions.featureNormalize(X)
X_norm,mu = Functions.featureNormalize(X);
m = X.shape[0] #Number of samples
p = np.mean(X_array,0); #Points centroid
p = np.array(p)[0] #p becomes an array
p_original = p/ConstPixelSpacing

iteration number 2


In [8]:
post_para[8]

array(['SampleG', '-0.999892571968', '-0.00809872918969',
       '-0.0122170008352', '-247.763470092'], 
      dtype='|S17')

In [32]:
ConstPixelSpacing

[0.49475097656299993, 0.49475097656299993, 4.9999995231628409]

In [22]:
a,b,c,d = pre_para[8][1],pre_para[8][2],pre_para[8][3],pre_para[8][4]

In [23]:
q  = np.zeros((3,1));
q[0],q[1],q[2] = a,b,c;

In [24]:
d = d.astype(float)
p_original_opt = np.array([245.58266437,  252.30278189,   13.4121527])

In [25]:
q = q.astype(float)

In [26]:
a_i,b_i,c_i = q[0]/ConstPixelSpacing[0],q[1]/ConstPixelSpacing[1],q[2]/ConstPixelSpacing[2]

In [27]:
np.divide(q,ConstPixelSpacing)

array([[-2.00460284, -2.00460284, -0.19835586],
       [ 0.25745554,  0.25745554,  0.02547528],
       [ 0.02469323,  0.02469323,  0.0024434 ]])

In [28]:
q_i  = np.zeros((3,1));
q_i[0],q_i[1],q_i[2] = a_i,b_i,c_i;
q0 = Functions.unit_vector(q_i)

In [29]:
d_i = np.dot(p_original_opt,q0)

In [30]:
q0,q

(array([[-0.99185251],
        [ 0.12738579],
        [ 0.00120896]]), array([[-0.99177921],
        [ 0.12737638],
        [ 0.012217  ]]))

In [31]:
a_i,b_i,c_i = q0[0],q0[1],q0[2]

In [21]:
crossShape = bone[:,:,10].shape
mask = np.zeros(bone.shape)
for i in range(bone.shape[2]):
    mask1 = np.fromfunction(lambda x,y: x > ((d_i-i*c_i-y*b_i)/a_i-2), crossShape)
    mask2 = np.fromfunction(lambda x,y: x < ((d_i-i*c_i-y*b_i)/a_i+2), crossShape)
    maski = np.multiply(mask1, mask2)
    mask[:,:,i] = maski
saveMask(mask,path,'reshapingfactor1')

In [89]:
path

'/Volumes/FAIR/Sinead/DC-Project-Images/original/SampleB/SB_Pre-op.nrrd'

In [91]:
q0 = Functions.unit_vector(q_i)
q0

array([[-0.99924298],
       [-0.0239387 ],
       [ 0.03066596]])

In [92]:
q

array([[-0.99590895],
       [-0.02385882],
       [ 0.08715574]])